server:
  port: 8081
  servlet:
    context-path: /goodbooks

spring:
  datasource:
    url: jdbc:h2:mem:infodb
    driverClassName: org.h2.Driver
    username: user
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2